# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c7c69ae7b7e82f76a77557206aec4ae7bd101a64f66c23ec6bb93769f73bf054787f89278650ec0d5d7355ba03e978102b5c6a9d34b2de0bdc471fbbd06bc0
  #the service_id allows this service to identify itself to other services
  service_id: 124290E9-42EF-4ACC-9C8B-D01AE5ED6828
test:
  secret_key_base: 6f961c5ebc56ed0549577eb70d49a7c483e619dd58806f2673b7dbe7a3cc12f3f95dce6ec45b5db987e341c0e88aae7a2059a487ced37cf5de22215b02263460
  service_id: F182CC8B-DE9F-4B5F-919F-90413C2E87A0

ua_test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>
