# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa098d5e9d5247a33a58e861ff75f7e22a7c5c96027f39efd12e144f34a31423d3aacf45ab79d2c7196907161ec957cd54352b085371b65a32a0e8acf8894e6
  #the service_id allows this service to identify itself to other services
  service_id: 342c075a-7aca-4c35-b3f5-29f043884b5b
  ldap_host: <%= ENV['LDAP_HOST'] %>
  ldap_port: <%= ENV['LDAP_PORT'] %>
  ldap_base: <%= ENV['LDAP_BASE'] %>

test:
  secret_key_base: 6f961c5ebc56ed0549577eb70d49a7c483e619dd58806f2673b7dbe7a3cc12f3f95dce6ec45b5db987e341c0e88aae7a2059a487ced37cf5de22215b02263460
  service_id: F182CC8B-DE9F-4B5F-919F-90413C2E87A0
  ldap_host: <%= ENV['LDAP_HOST'] %>
  ldap_port: <%= ENV['LDAP_PORT'] %>
  ldap_base: <%= ENV['LDAP_BASE'] %>

ua_test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>
  ldap_host: <%= ENV['LDAP_HOST'] %>
  ldap_port: <%= ENV['LDAP_PORT'] %>
  ldap_base: <%= ENV['LDAP_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>
  ldap_host: <%= ENV['LDAP_HOST'] %>
  ldap_port: <%= ENV['LDAP_PORT'] %>
  ldap_base: <%= ENV['LDAP_BASE'] %>
